### PR TITLE
Add free browser for android

### PR DESCRIPTION
**Pull request by n-ce**

### CODE REVIEW

**Comment by ner00** [comment]
Kiwi browser for Android is also a valid option.

**Comment by n-ce** [comment]
> Not important, thanks anyway.

Did not expect that, so you are indirectly preferring to promote a closed source application than add an open source option.

**Comment by iamfugui** [comment]
> > Not important, thanks anyway.
> 
> Did not expect that, so you are indirectly preferring to promote a closed source application than add an open source option.

https://github.com/tuyafeng/Via

**Comment by n-ce** [comment]
> > > Not important, thanks anyway.
> > 
> > 
> > Did not expect that, so you are indirectly preferring to promote a closed source application than add an open source option.
> 
> https://github.com/tuyafeng/Via

Only the translation resources are open source not the app itself.

**Comment by ner00** [comment]
If anything, rather than promoting a closed source browser or an unproven open source one like Free, Kiwi seems like a much better alternative that has been around for a while.

**Pull request closed without merging**
